from typing import List, Dict, Any
from abc import ABC, abstractmethod
import random

class LLMInterface(ABC):
    """Abstract interface for LLM interaction."""
    @abstractmethod
    def generate(self, prompt: str) -> str:
        pass

class MockLLM(LLMInterface):
    """Mock LLM for testing without real API keys."""
    def generate(self, prompt: str) -> str:
        # Simple heuristic response based on prompt keywords to simulate behavior
        if "Task-Agnostic Steps" in prompt:
            return "- Define requirements\n- Design architecture\n- Implement core logic"
        if "Design Brief" in prompt or "Aurora" in prompt:
            return "Design Brief:\n- Primary Color: #336699\n- Typography: Inter\n- Layout: Clean, Grid-based"
        if "python code" in prompt.lower() or "implementation" in prompt.lower():
            return "def implemented_function():\n    print('Code generated by Kodax')"
        return f"[LLM Response] Processed prompt of length {len(prompt)}"

class Agent:
    """Represents an AI Agent with a specific role and goal."""
    
    def __init__(self, name: str, role: str, goal: str, prompt_template: str, llm: LLMInterface = None):
        self.name = name
        self.role = role
        self.goal = goal
        self.prompt_template = prompt_template
        self.llm = llm or MockLLM()
        
    def execute(self, context: Dict[str, Any], tools: List[Any] = None) -> Any:
        """Executes the agent's task. If a tool is provided, it uses the tool."""
        print(f"[{self.name}] Executing task...")
        
        # Gen 4/5 Logic: If a tool is strictly assigned, use it.
        if tools and len(tools) > 0:
            tool = tools[0]
            # Heuristic: Pass context as kwargs if keys match, 
            # or if context has 1 item and tool takes something else, pass value.
            # Simplified: Pass *values* if 1 item, else **kwargs.
            if len(context) == 1:
                arg_val = list(context.values())[0]
                try:
                    # Try passing as single argument
                    return tool.run(arg_val)
                except TypeError:
                    # Fallback to kwargs
                    return tool.run(**context)
            else:
                 return tool.run(**context)

        # Fallback to LLM generation (Gen 4 Base)
        prompt = self._build_prompt(context)
        response = self.llm.generate(prompt)
        print(f"[{self.name}] Finished.")
        return response

    def _build_prompt(self, context: Dict[str, Any]) -> str:
        prompt = self.prompt_template
        for key, value in context.items():
            placeholder = "{{" + key + "}}" # e.g., {{current_goal}}
            if placeholder in prompt:
                # Handle lists gracefully in prompt
                val_str = str(value)
                prompt = prompt.replace(placeholder, val_str)
        return prompt

class AgentRegistry:
    """Registry to manage available agents."""
    
    def __init__(self):
        self._agents: Dict[str, Agent] = {}

    def register(self, agent: Agent):
        self._agents[agent.name] = agent

    def get_agent(self, name: str) -> Agent:
        return self._agents.get(name)
