from typing import List, Dict, Any
from abc import ABC, abstractmethod
import random

class LLMInterface(ABC):
    """Abstract interface for LLM interaction."""
    @abstractmethod
    def generate(self, prompt: str) -> str:
        pass

class MockLLM(LLMInterface):
    """Mock LLM for testing without real API keys."""
    def generate(self, prompt: str) -> str:
        # Simple heuristic response based on prompt keywords to simulate behavior
        if "Task-Agnostic Steps" in prompt:
            return "- Define requirements\n- Design architecture\n- Implement core logic"
        if "Design Brief" in prompt or "Aurora" in prompt:
            return "Design Brief:\n- Primary Color: #336699\n- Typography: Inter\n- Layout: Clean, Grid-based"
        if "python code" in prompt.lower() or "implementation" in prompt.lower():
            return "def implemented_function():\n    print('Code generated by Kodax')"
        return f"[LLM Response] Processed prompt of length {len(prompt)}"

class Agent:
    """Represents an AI Agent with a specific role and goal."""
    
    def __init__(self, name: str, role: str, goal: str, prompt_template: str, llm: LLMInterface = None):
        self.name = name
        self.role = role
        self.goal = goal
        self.prompt_template = prompt_template
        self.llm = llm or MockLLM()
        
    def execute(self, context: Dict[str, Any]) -> str:
        """Executes the agent's task by populating the prompt and calling the LLM."""
        prompt = self._build_prompt(context)
        print(f"[{self.name}] Executing task...")
        response = self.llm.generate(prompt)
        print(f"[{self.name}] Finished.")
        return response

    def _build_prompt(self, context: Dict[str, Any]) -> str:
        prompt = self.prompt_template
        for key, value in context.items():
            placeholder = "{{" + key + "}}" # e.g., {{current_goal}}
            if placeholder in prompt:
                prompt = prompt.replace(placeholder, str(value))
        return prompt

class AgentRegistry:
    """Registry to manage available agents."""
    
    def __init__(self):
        self._agents: Dict[str, Agent] = {}

    def register(self, agent: Agent):
        self._agents[agent.name] = agent

    def get_agent(self, name: str) -> Agent:
        return self._agents.get(name)
